---
name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install OpenFOAM
        run: |
          sudo apt-get update
          sudo apt-get install -y openfoam
        shell: bash
      - name: Build solver
        run: |
          source /usr/lib/openfoam/openfoam*/etc/bashrc
          wmake
        shell: bash
      - name: Run simple case
        run: |
          source /usr/lib/openfoam/openfoam*/etc/bashrc
          compInterFoam -help
        shell: bash
